module.exports = [
  {
    name: "Accounting & Consulting",
    items: [
      "Business Analysis",
      "Management Consulting",
      "Instructional Design",
      "HR Administration",
      "Recruiting",
      "Training & Development",
      "Lifestyle Coaching",
      "Tax Preparation",
      "Accounting",
      "Bookkeeping",
      "Financial Management/CFO",
      "Financial Analysis & Modeling",
    ],
  },
  {
    name: "Admin Support",
    items: [
      "Personal Virtual Assistance",
      "Executive Virtual Assistance",
      "Legal Virtual Assistance",
      "Other Virtual Assistance",
      "Medical Virtual Assistance",
      "General Virtual Assistance",
      "Data Entry",
      "Other Data Entry & Transcription Services",
      "Transcription",
      "Dropshipping & Order Processing",
      "General Project Management",
      "Construction & Engineering Project Management",
      "Other Project Management",
      "Development & IT Project Management",
      "Healthcare Project Management",
      "Quantitative Research",
      "Other Research & Product Reviews",
      "Market Research",
      "General Research Services",
      "Qualitative Research",
      "Product Reviews",
      "Web & Software Product Research",
    ],
  },
  {
    name: "Customer Service",
    items: [
      "Customer Onboarding",
      "Other Customer Experience & Tech Support",
      "IT Support",
      "Customer Success",
      "Tech Support",
      "Email, Phone & Chat Support",
      "Visual Tagging & Processing",
      "Community Management",
      "Other Community Management & Tagging",
      "Content Moderation",
    ],
  },
  {
    name: "Data Science & Analytics",
    items: [
      "Data Mining",
      "Data Engineering",
      "Data Visualization",
      "Data Extraction",
      "Data Processing",
      "Deep Learning",
      "Knowledge Representation",
      "Machine Learning",
      "A/B Testing",
      "Data Analytics",
      "Experimentation & Testing",
    ],
  },
  {
    name: "Design & Creative",
    items: [
      "Data Mining",
      "Data Engineering",
      "Data Visualization",
      "Data Extraction",
      "Data Processing",
      "Deep Learning",
      "Knowledge Representation",
      "Machine Learning",
      "A/B Testing",
      "Data Analytics",
      "Experimentation & Testing",
    ],
  },
  {
    name: "Engineering & Architecture",
    items: [
      "Structural Engineering",
      "Building Information Modeling",
      "Civil Engineering",
      "3D Modeling & Rendering",
      "CAD",
      "Structural Architecture",
      "Landscape Architecture",
      "Interior Design",
      "Trade Show Design",
      "Energy Engineering",
      "Mechanical Engineering",
      "Chemical & Process Engineering",
      "Electrical Engineering",
      "Electronic Engineering",
      "STEM Tutoring",
      "Physics",
      "Mathematics",
      "Biology",
      "Chemistry",
      "Logistics & Supply Chain Management",
      "Sourcing & Procurement",
    ],
  },
  {
    name: "IT & Networking",
    items: [
      "Network Security",
      "IT Compliance",
      "Information Security",
      "Database Administration",
      "Cloud Engineering",
      "Solutions Architecture",
      "DevOps Engineering",
      "Business Applications Development",
      "Systems Engineering",
      "Systems Administration",
      "Network Administration",
    ],
  },
  {
    name: "Legal",
    items: [
      "General Counsel",
      "Business & Corporate Law",
      "Intellectual Property Law",
      "Paralegal Services",
      "Tax Law",
      "Securities & Finance Law",
      "Labor & Employment Law",
      "Regulatory Law",
      "International Law",
      "Immigration Law",
    ],
  },
  {
    name: "Sales & Marketing",
    items: [
      "Social Media Strategy",
      "Marketing Strategy",
      "Content Strategy",
      "Brand Strategy",
      "Social Media Marketing",
      "Public Relations",
      "Email Marketing",
      "Marketing Automation",
      "Campaign Management",
      "Digital Marketing",
      "Search Engine Marketing",
      "Search Engine Optimization",
      "Telemarketing",
      "Lead Generation",
      "Sales & Business Development",
    ],
  },
  {
    name: "Translation",
    items: [
      "Medical Document Translation",
      "Legal Document Translation",
      "Technical Document Translation",
      "Language Tutoring",
      "General Translation Services",
      "Language Localization",
    ],
  },
  {
    name: "Web, Mobile & Software Dev",
    items: [
      "Ecommerce Website Development",
      "Desktop Software Development",
      "Scripting & Automation",
      "Manual Testing",
      "Automation Testing",
      "Mobile App Development",
      "Mobile Game Development",
      "Prototyping",
      "Mobile Design",
      "Web Design",
      "UX/UI Design",
      "Crypto Coins & Tokens",
      "Blockchain & NFT Development",
      "Other Blockchain, NFT & Cryptocurrency",
      "Crypto Wallet Development",
      "Firmware Development",
      "Emerging Tech",
      "AR/VR Development",
      "Coding Tutoring",
      "Database Development",
      "Agile Leadership",
      "Scrum Leadership",
      "Back-End Development",
      "Front-End Development",
      "Full Stack Development",
      "CMS Development",
      "Video Game Development",
    ],
  },
  {
    name: "Writing",
    items: [
      "Editing & Proofreading",
      "Career Coaching",
      "Scriptwriting",
      "Creative Writing",
      "Ghostwriting",
      "Grant Writing",
      "Technical Writing",
      "Business Writing",
      "Writing Tutoring",
      "Content Writing",
      "Copywriting",
    ],
  },
];
